sudo apt install -y cmatrix
sudo apt install -y curl
sudo apt install -y fuse
sudo apt install -y git
sudo apt install -y hollywood
sudo apt install -y keepassxc
sudo apt install -y php
sudo apt install -y neofetch
sudo apt install -y qbittorrent
sudo apt install -y ruby
sudo apt install -y vlc
sudo apt install -y wireshark
